### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by masterpowers** [nepster-web/php-mlm-matrix#1]
Im Using Laravel as my Framework to Implement Your Script.
What i Did Was Put the Matrix.php in My MODEL.

users->hasmany(LINKS)
links->hasmany(matrix)

with this kind of relationship

i did this coz i want to have 1 user that can purchase many link to fill up the matrix.

Render.php to RenderController
Just implement  Matrix namespace

use App/Matrix;

While Your Matrix.Sql to Laravel Migration Create_matrix_table , Create_matrix_links_table and create_matrix_type_table

Can You Provide me a Demo site? where all the function is working.
Or a Procedural Way to Implement each function
So i will know What a Function Do, and How i can Render it properly and integrate with properly with laravel.

Looking Forward for Your Reply

**Comment by nepster-web** [comment]
Hi, i don't know much about english. I use https://translate.google.ru.
Maybe I misunderstood you.

Do you want find all matrix for  user using Laravel or you need a description and examples of matrix functions ?

**Comment by masterpowers** [comment]
я хотел бы видеть демо приложения о том, как вы используете все функции, и как вы интегрировать его с пользователей модели.

Есть ли у вас исходный код для демо или производственной площадке.
Я хочу посмотреть, как вы называете функции.

Так я могу реализовать его с Laravel правильно.

Спасибо

**Comment by masterpowers** [comment]
Да, я хочу, чтобы найти все матрицы для пользователя с помощью Laravel и нуждаются описание и примеры матричных функций

**Comment by nepster-web** [comment]
I understand how you read my translation =).

I will practice English.

I do not have examples now, but I can make you an example matrix code. 
I do not use Laravel, I use Yii2. 

Can I use yii2 or a pure php ?

On the weekends, I like to demonstrate example.

**Comment by masterpowers** [comment]
Я хотел бы видеть его в рамках Yii и чистого PHP,
Так я могу проверить, как я могу реализовать его в Laravel.
Спасибо

**Comment by nepster-web** [comment]
@masterpowers I'm sorry, I did not have time today.
I will prepare a simple example of tomorrow

**Comment by masterpowers** [comment]
thanks looking forward for it

**Comment by nepster-web** [comment]
@masterpowers 

I have much work but I have prepared a small example in pure php:
http://demo.nepster.pro/matrix/

Code example: http://demo.nepster.pro/matrix/index.txt

If you can do it in Laravel, I'll show you how to divide matrix.

P.S. 
Matrix array you need to store and selected out of here https://github.com/nepster-web/php-mlm-matrix/blob/master/shema/matrix.sql#L43

**Comment by masterpowers** [comment]
Hi when i var_dump the

**Comment by masterpowers** [comment]
I Have managed to load the View for the First Matrix
$matricesHtml = MatricesHtml::renderMatrix($matrix);

When i use Var_dump on 
var_dump($matricesHtml);

the return value is this
http://pastebin.com/sYtW9dQG

Here is the Image of the Matrix
http://imgur.com/cBoJszg

Are you Also getting the same var_dump as mine?
Since i just copied  your sample code.
Or Am i Missing some Code?
Or do i need to Divide the Matrix?

**Comment by nepster-web** [comment]
**Matrix.php** - This class works with matrices.

This code generates a matrix:

```
$matrix = new Matrix(2, 3);
$matrix->generation($users, function ($l, $n, $user, $matrix) {
    $user['position'] = $matrix->getPosition($user['level'], $user['number']);
    $user['myParam'] = 'myValue'; // Add personal params
    return $user;
});
$matrix->getArray() - this function return matrix array.
```

Your matrix here:

```
echo '<pre>';
print_r($matrix->getArray());
echo '</pre>';
```

Now you need to generate html code for your matrix.

You can help class **_Render.php**_.

Class Render accepts an matrix object, and converts it to html. After you have to insert the result on your page.

**Comment by nepster-web** [comment]
you understand my English or I go on a training ?

**Comment by masterpowers** [comment]
yup i already render the matrix,  i want to go to next step. like you said. You are going to teach me how to divide the matrix after it was filled. looking forward for that

**Comment by nepster-web** [comment]
I create a project on matrices. Wait updates and new methods. I can set an example of matrix division at the weekend.

**Comment by nepster-web** [comment]
I'm sorry I'm very busy. I need more time.

**Comment by masterpowers** [comment]
no problem

**Comment by masterpowers** [comment]
ANy Updates :)

**Comment by nepster-web** [comment]
Excuse me. I worked a lot. What to tell you?

**Comment by AdebisiJoe** [comment]
please how do we have do i divide the matrix after its filled please i really need this

**Comment by nepster-web** [comment]
@AdebisiJoe hello. Excuse me, I'm busy now. But I will be able to answer you until tomorrow.

**Comment by AdebisiJoe** [comment]
ok thanks stil expecting

**Comment by nepster-web** [comment]
View example:
http://demo.nepster.pro/matrix/

Code example:
http://demo.nepster.pro/matrix/index.txt

if you need to split the matrix you need to use the method **division();**

``` php

// You need to generate an array
$users = [
    [
        'level' => 0, // This key is required
        'number' => 0,  // This key is required
        'user' => 'Nepster',
        'avatar' => 'https://avatars0.githubusercontent.com/u/5681979?v=3&s=96',
    ],
    [
        'level' => 1, // This key is required
        'number' => 0,  // This key is required
        'user' => 'masterpowers',
        'avatar' => 'https://avatars0.githubusercontent.com/u/5681979?v=3&s=96',
    ],
];


// Create new mlm matrix
/**
 * $view
 * $levels
 */
$matrix = new Matrix(2, 3);

// Custom function for generation matrix array
$matrix->generation($users, function ($l, $n, $user, $matrix) {
    $user['position'] = $matrix->getPosition($user['level'], $user['number']);
    $user['myParam'] = 'myValue'; // Add personal params
    return $user;
});

$matricesHtml[] = renderMatrix($matrix);


$newMatrices = $matrix->division();
```

The result is a new array of matrices. 

If you need more detailed documentation in English I can try to do it. But I still bad know in English.
