### ISSUE TITLE
i want to integrate MLM Matrix.function

### ISSUE THREAD

**Issue by bethechange0474** [nepster-web/php-mlm-matrix#2]
thanks for your reply sir..am using pure PHP of a membership script with i want to integrate MLM Matrix.function with, cos am a beginner it too logical for me to understand how to integrate MLM Matrix.i saw your script which i like the database table but i dont understand the matrix.php file, please sir can you just show me how to add data of user in Matrix table and there downline and  also query matrix_users table...thank God bless you

Спасибо за ответ sir..am с использованием чистого PHP скрипта членства с я хочу, чтобы интегрировать MLM Matrix.function с, потому новичок это слишком логично для меня, чтобы понять, как интегрировать MLM Matrix.i увидел сценарий, который я люблю таблица базы данных, но я не понимаю, файл matrix.php, пожалуйста, сэр, вы можете просто показать мне, как добавить данные пользователя в матричной таблице и там нижестоящих, а также запрос matrix_users таблицу ... слава Богу благословить вас

**Comment by nepster-web** [comment]
Let's try to understand.

1) Do not use the Google translator for translations into Russian. =) 
if you need a translation into Russian, use https://translate.yandex.ru

2) if you are a beginner, you should know the specifications:
http://www.php-fig.org/psr/
https://getcomposer.org/

and I recommend using framework for example: https://laravel.com/ or http://www.yiiframework.com/ .

3) But if you want pure PHP, then:
Code example: http://demo.nepster.pro/matrix/index.txt and demo view http://demo.nepster.pro/matrix/

And a question for you: do you understand my bad English ?

**Comment by bethechange0474** [comment]
Спасибо Вам за вашу поддержку я бегу index.txt вы даете мне, что его работа да благословит вас Бог

а также ваш английский и понятно, еще раз спасибо

**Comment by nepster-web** [comment]
Speak English Please. This Russian translation is more difficult to understand.
if you have got any questions, please contact me. 

I train my English skill speaking with you. =)

**Comment by AdebisiJoe** [comment]
hi my name is Joseph and  i really need your help with the mlm matrix system i need to know how to use the division system and the database please you help will be appreciated thanks God bless

**Comment by nepster-web** [comment]
@AdebisiJoe Do you use framework or pure PHP ?

**Comment by AdebisiJoe** [comment]
i am using laravel 5.2 any way you can help so sorry for the late reply i have been busy please need to integrate this using a 7 by 7 matrix system i am having difficulty with understanding your code please help

**Comment by nepster-web** [comment]
This library is used in pure PHP. If you want to use it in laravel5, you need to create a migrations of the scheme (https://github.com/nepster-web/php-mlm-matrix/blob/master/shema/matrix.sql). 

Also, don't forget to install the library using composer:

```
"nepster-web/php-mlm-matrix": "*"
```

Create the necessary models for the entities (MatrixType, Matrix, MatrixUser).

And look at the implementation of the example:
http://demo.nepster.pro/matrix/index.txt
You don't need function "spl_autoload_register".

**Do you need documentation in English ?**

**Comment by AdebisiJoe** [comment]
please this is Joseph please can you demonstrate how to use division of matrix with this script

**Comment by VasquezSRE** [comment]
Hello,

I need use with laravel 5.2 with matrix 2x5 , and not find documention for integrations

**Comment by nepster-web** [comment]
Hello. it's a library in pure php.
You need to write a wrapper by laravel5 yourself. I can advise you.

**Comment by cesarpalacio** [comment]
Hi, sorry my English but the examples not working:
Code example: http://demo.nepster.pro/matrix/index.txt and demo view http://demo.nepster.pro/matrix/

**Comment by nepster-web** [comment]
My apologies. Time of payment for hosting is over. I haven't  time to do this now.

**Comment by cesarpalacio** [comment]
Okay, I understand, thank you.
