### ISSUE TITLE
Не понимаю как работает матрица

### ISSUE THREAD

**Issue by emetelyov** [nepster-web/php-mlm-matrix#3]
Привет,

В основном работаю с Codeigniter, есть задача сделать матрицу с выплатами, чем выше уровень тем выше выплата, как мне правильно использовать твой код, для реализации этой функции?

С уважением.
Евгений

**Comment by nepster-web** [comment]
привет. Нужна более подробная информация о "есть задача сделать матрицу с выплатами, чем выше уровень тем выше выплата". 

Данный скрипт рассчитан на небольшие матрицы с делением. Например, если есть матрица:

 ```
   1
  23
 4567
```

С помощью данной библиотеки ее можно отрендерить или поделить вот так:

 ```
   2            3 
   45           67
  0000         0000
```

Тем самым получается, что всегда работа идет с небольшой матрицей, обычно это двоичная четырехуровневая или троичная четырехуровневая.
