### ISSUE TITLE
Есть ли примеры работы с sql

### ISSUE THREAD

**Issue by NigmetovTimur** [nepster-web/php-mlm-matrix#4]
Доброго времени суток. Есть ли примеры работы с sql таблицей?

**Comment by nepster-web** [comment]
Приветствую. Вы про это? 
https://github.com/nepster-web/php-mlm-matrix/blob/master/shema/matrix.sql

**Comment by NigmetovTimur** [comment]
ага, но я просто не понял как использовать callback функцию к примеру вытянул я айдихи юзеров и их спонсоров, но как дальше формировать структуру.
Вижу конечно пример тут https://yadi.sk/i/vurzteGJ3TjzDr
Но немного не понял как его связать с Вашей таблицей.

**Comment by nepster-web** [comment]
В данной библиотеке нет такого решения. Тоесть вам нужно самостоятельно делать чтение или запись в сторедж. 
Через несколько месяцев я планирую начать делать апгрейд данной библиотеки с более подробной  документацией.

**Comment by NigmetovTimur** [comment]
Окей. Спасибо. Буду ждать
