### ISSUE TITLE
Есть ли "перелив" в матрицах?

### ISSUE THREAD

**Issue by XAPKIB** [nepster-web/php-mlm-matrix#6]
Здравствуйте! 
У меня к вам два вопроса.

1.Обычно в бинарных  (2х2) и троичных (3х3) матрицах есть так называемый "перелив", когда партнер привлекает больше партнеров первой линии (больше 2 или 3), то эти новые партнеры регистрируются под одним из партнеров его первого уровня... в Вашей библиотеке такое реализовано? В описании не нашел, а в код глубако не вникал.

2. Как подключить библиотеку на сайт с реализацией через MySQL? Не сильно знаком с композером и его использованием, при этом Ваши рекомендации 2016 года посмотреть на http://demo.nepster.pro/matrix/ на данный момент не актуальны, сервер выдает 404 ошибку.

**Comment by nepster-web** [comment]
Приветствую. 
1. Не уверен, что вас правильно понял, но вы имеете ввиду, что если на примере 3x3 матрицы, пользователь с 2 уровня центральной позиции приглашает 3 новых пользователей, то они станут под ним в 3 уровень (по центру)?

2. Это достаточно низкоуровневая библиотека, мы не разрабатывал работу с хранилищами, так-как есть очень много условий в подобных проектах. Вам нужно сделать это самостоятельно. Например сервисом, которой будет доставать данные из базы и восстанавливать из них объект матрицы и наоборот, брать объект матрицы, доставать данные и записывать в базу. 
 

Вот пример описания вот этого дела:
```php
class MatrixService {

    public function findById(int $id): Matrix
    {
        // You need make a query to the `matrix` table that find the required record
        // Use join or another query to retrieve user data from the `matrix_users` table
        // Initialize new Matrix object
        // Using `addTenant` method that add users to Matrix object (based on data from `matrix_users` table)
        // Return the proper Matrix object
    }

    public function save(Matrix $matrix): void
    {
        // Get the matrix array using the `$matrix->toArray()` method
        // Create a valid request to save data to the database
        // - Most likely in a relational database you will have 2 tables (matrices and matrix_users)
        // - Don`t forget to check a new matrix is being created or edited an already existing matrix
        
        // Note1: Write down users with depth and number for further recovery
        // Note2: Don`t write coordinates with empty positions to the database.
    }

}
```

**Comment by XAPKIB** [comment]
1. Попытаюсь объяснить на матрице 2х2. У партнера есть обязательство лично привлечь двух партнеров под себя, он привлек, например, троих (может и больше). Два идут под него в "левую" и "правую" ветку, а тот третий идет в "слабую" ветку, т.е. туда, где нет никого или меньше партнеров на данный момент. Это классическое правило в млм-бинарах и матричных схемах.

2. Да, приведенный Вами код я видел, понял, что надо запрашивать данные и записывать. Меня интересует подключение библиотеки к исполнительному PHP файлу. Обычно я загружаю класс или библиотеку и подключаю её в файле каким-то таким образом:
```
include('mymlmbinary.class.php'); 
$mybinary = new mlmBinary(); 
```

А вот что делать с этим кодом, не пойму:

```
use Nepster\Matrix\Coord;
use Nepster\Matrix\Matrix;
use Nepster\Matrix\MatrixRender;
use Nepster\Matrix\MatrixManager;
use Nepster\Matrix\MatrixPositionManager;
include '../vendor/autoload.php';
```

**Comment by nepster-web** [comment]
1. нет такая штука не предусмотрена, ее нужно делать самостоятельно. Пользуясь  MatrixPositionManager. Тоесть логика примерно такая, при активации пользователя в матрицу, ваша логика должна определить для него нужную позицию и только потом в игру вступает сама библиотека

2. Вам нужно использовать composer. Это считается не то, что бест-практис, а теперь обязательное условие при разработки приложений/проектов.  
Так-же обратите внимание, что минимальная версия php для работы с библиотекой 7.2

**Comment by XAPKIB** [comment]
Хорошо, спасибо! Пошёл изучать...

**Comment by nepster-web** [comment]
Обращайтесь
