### ISSUE TITLE
Matrix structure limits

### ISSUE THREAD

**Issue by antonkomarev** [nepster-web/php-mlm-matrix#8]
Why is it limited to 2x2 and 3x3?

**Comment by nepster-web** [comment]
I worked for long time with matrices and there was always 2x2 and 3x3 power.
So, this library is not designed to work with trees. So you probably won't be able to render big data.
However, I don't remember that I make restrictions other than the render class.

**Comment by bookpowers** [comment]
Where would I be able to find a forced matrix?
