### ISSUE TITLE
Mysql schema

### ISSUE THREAD

**Issue by fadlisaad** [nepster-web/php-mlm-matrix#9]
Hi, I noticed there are 2 fields in matrix_users table, namely `depth` and `number`. May I know what should we put in `number?`? Is it the number of the position?

**Comment by nepster-web** [comment]
oh, I did not translate comments in the MySql schema, sorry. 
depth - it is your level in the matrix. 
number - your number in level. 

For example:
.....0.....
...012...
0123456

This matrix consists of 3 levels. Each level has numbers.  
Now we can work with coordinates. For example:
Level:1 number: 2
.....0.....
...01(x)...
0123456

**Comment by fadlisaad** [comment]
Cool, now I got it. Great plugin to start with. So what is the maximum depth this can support?
--ANSWER: I've made test, it infinite!

**Comment by nepster-web** [comment]
Thank you.
